#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'os'
    style = 'diamond'
    foreground = '#011627'
    background = '#21c7a8'
    leading_diamond = '╭─'
    trailing_diamond = ''
    template = ' {{ if .WSL }}WSL at {{ end }}{{.Icon}}  '

  [[blocks.segments]]
    type = 'path'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#011627'
    background = '#82AAFF'
    template = '{{ path .Path .Location }}'

    [blocks.segments.properties]
      folder_icon = ' '
      folder_separator_icon = '<#011627></> '
      home_icon = '  '
      style = 'agnoster'

  [[blocks.segments]]
    type = 'git'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#011627'
    background = '#addb67'
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}#e4cf6a{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#f78c6c{{ end }}', '{{ if gt .Ahead 0 }}#C792EA{{ end }}', '{{ if gt .Behind 0 }}#c792ea{{ end }}']
    template = ' {{ url .UpstreamIcon .UpstreamURL }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '

    [blocks.segments.properties]
      branch_icon = ' '
      fetch_stash_count = true
      fetch_status = true
      fetch_upstream_icon = true
      fetch_worktree_count = true


[[blocks]]
  type = 'prompt'
  alignment = 'right'
  overflow = 'break'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'diamond'
    foreground = '#d6deeb'
    background = '#575656'
    leading_diamond = ''
    trailing_diamond = '<transparent,#575656></>'
    template = ' {{ .FormattedMs }}'

    [blocks.segments.properties]
      style = 'roundrock'
      threshold = 0.0
  [[blocks.segments]]
    type = 'angular'
    style = 'diamond'
    foreground = '#ce092f'
    background = '#ffffff'
    leading_diamond = ''
    trailing_diamond = '<transparent,#ffffff></>'
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '

  [[blocks.segments]]
    type = 'aws'
    style = 'diamond'
    foreground = '#faa029'
    background = '#565656'
    leading_diamond = ''
    trailing_diamond = '<transparent,#565656></>'
    template = ' {{ .Profile }}{{ if .Region }}@{{ .Region }}{{ end }} '

  [[blocks.segments]]
    type = 'az'
    style = 'diamond'
    foreground = '#337bb6'
    background = '#ffffff'
    leading_diamond = ''
    trailing_diamond = '<transparent,#ffffff></>'
    template = ' {{ .EnvironmentName }} '

  [[blocks.segments]]
    type = 'azfunc'
    style = 'diamond'
    foreground = '#5398c2'
    background = '#ffffff'
    leading_diamond = ''
    trailing_diamond = '<transparent,#ffffff></>'
    template = '<#f5bf45></> {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '

  [[blocks.segments]]
    type = 'cds'
    style = 'diamond'
    foreground = '#100e23'
    background = '#5a7a94'
    leading_diamond = ''
    trailing_diamond = '<transparent,#5a7a94></>'
    template = '  cds {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '

  [[blocks.segments]]
    type = 'crystal'
    style = 'diamond'
    foreground = '#000000'
    background = '#ffffff'
    leading_diamond = ''
    trailing_diamond = '<transparent,#000000></>'
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '

  [[blocks.segments]]
    type = 'cf'
    style = 'diamond'
    foreground = '#1d5185'
    background = '#ffffff'
    leading_diamond = ''
    trailing_diamond = '<transparent,#ffffff></>'
    template = '  cf {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '

  [[blocks.segments]]
    type = 'cftarget'
    style = 'diamond'
    foreground = '#1d5185'
    background = '#ffffff'
    leading_diamond = ''
    trailing_diamond = '<transparent,#ffffff></>'
    template = ' {{if .Org }}{{ .Org }}{{ end }}{{ if .Space }}/{{ .Space }}{{ end }} '

  [[blocks.segments]]
    type = 'cmake'
    style = 'diamond'
    foreground = '#01a300'
    background = '#d2d2d2'
    leading_diamond = ''
    trailing_diamond = '<transparent,#d2d2d2></>'
    template = '<#2829b2></> <#be1818></>  cmake {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '

  [[blocks.segments]]
    type = 'dart'
    style = 'diamond'
    foreground = '#055b9c'
    background = '#e1e8e9'
    leading_diamond = ''
    trailing_diamond = '<transparent,#e1e8e9></>'
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '

  [[blocks.segments]]
    type = 'dotnet'
    style = 'diamond'
    foreground = '#0d6da8'
    background = '#0e0e0e'
    leading_diamond = ''
    trailing_diamond = '<transparent,#0e0e0e></>'
    template = '  {{ if .Unsupported }}{{ else }}{{ .Full }}{{ end }} '

  [[blocks.segments]]
    type = 'flutter'
    style = 'diamond'
    foreground = '#ffffff'
    background = '#06A4CE'
    leading_diamond = ''
    trailing_diamond = '<transparent,#06A4CE></>'
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '

  [[blocks.segments]]
    type = 'go'
    style = 'diamond'
    foreground = '#06aad5'
    background = '#ffffff'
    leading_diamond = ''
    trailing_diamond = '<transparent,#ffffff></>'
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '

  [[blocks.segments]]
    type = 'haskell'
    style = 'diamond'
    foreground = '#906cff'
    background = '#100e23'
    leading_diamond = ''
    trailing_diamond = '<transparent,#100e23></>'
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '

  [[blocks.segments]]
    type = 'java'
    style = 'diamond'
    foreground = '#ec2729'
    background = '#ffffff'
    leading_diamond = ''
    trailing_diamond = '<transparent,#ffffff></>'
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '

  [[blocks.segments]]
    type = 'julia'
    style = 'diamond'
    foreground = '#ffffff'
    background = '#945bb3'
    leading_diamond = ''
    trailing_diamond = '<transparent,#945bb3></>'
    template = '<#ca3c34></> {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '

  [[blocks.segments]]
    type = 'kotlin'
    style = 'diamond'
    foreground = '#ffffff'
    background = '#906cff'
    leading_diamond = ''
    trailing_diamond = '<transparent,#906cff></>'
    template = 'K {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '

  [[blocks.segments]]
    type = 'lua'
    style = 'diamond'
    foreground = '#000081'
    background = '#ffffff'
    leading_diamond = ''
    trailing_diamond = '<transparent,#ffffff></>'
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '

  [[blocks.segments]]
    type = 'node'
    style = 'diamond'
    foreground = '#3C873A'
    background = '#303030'
    leading_diamond = ''
    trailing_diamond = '<transparent,#303030></>'
    template = ' {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }} '

    [blocks.segments.properties]
      fetch_package_manager = true
      npm_icon = '<#cc3a3a></> '
      yarn_icon = '<#348cba></> '

  [[blocks.segments]]
    type = 'nx'
    style = 'diamond'
    foreground = '#1e293b'
    background = '#6488c0'
    leading_diamond = ''
    trailing_diamond = '<transparent,#6488c0></>'
    template = 'Nx {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '

  [[blocks.segments]]
    type = 'perl'
    style = 'diamond'
    foreground = '#ffffff'
    background = '#41436d'
    leading_diamond = ''
    trailing_diamond = '<transparent,#41436d></>'
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '

  [[blocks.segments]]
    type = 'php'
    style = 'diamond'
    foreground = '#000000'
    background = '#787CB5'
    leading_diamond = ''
    trailing_diamond = '<transparent,#787CB5></>'
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '

  [[blocks.segments]]
    type = 'python'
    style = 'diamond'
    foreground = '#FFE873'
    background = '#306998'
    leading_diamond = ''
    trailing_diamond = '<transparent,#306998></>'
    template = '  {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }}'

  [[blocks.segments]]
    type = 'r'
    style = 'diamond'
    foreground = '#1c68bd'
    background = '#b9bbbf'
    leading_diamond = ''
    trailing_diamond = '<transparent,#b9bbbf></>'
    template = 'R {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '

  [[blocks.segments]]
    type = 'ruby'
    style = 'diamond'
    foreground = '#9c1006'
    background = '#ffffff'
    leading_diamond = ''
    trailing_diamond = '<transparent,#ffffff></>'
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '

  [[blocks.segments]]
    type = 'rust'
    style = 'diamond'
    foreground = '#000000'
    background = '#ffffff'
    leading_diamond = ''
    trailing_diamond = '<transparent,#ffffff></>'
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '

  [[blocks.segments]]
    type = 'swift'
    style = 'diamond'
    foreground = '#ffffff'
    background = '#fe562e'
    leading_diamond = ''
    trailing_diamond = '<transparent,#fe562e></>'
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} '

  [[blocks.segments]]
    type = 'time'
    style = 'diamond'
    foreground = '#d6deeb'
    background = '#234d70'
    leading_diamond = ''
    trailing_diamond = ''
    template = ' {{ .CurrentDate | date .Format }}'

    [blocks.segments.properties]
      time_format = '15:04:05'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = '#21c7a8'
    template = '╰─'

  [[blocks.segments]]
    type = 'spotify'
    style = 'diamond'
    foreground = '#011627'
    background = '#1DB954'
    leading_diamond = ''
    trailing_diamond = ' '
    template = ' {{ .Icon }}{{ if ne .Status "stopped" }}{{ .Artist }} ~ {{ .Track }}{{ end }} '

    [blocks.segments.properties]
      playing_icon = ' '

  [[blocks.segments]]
    type = 'status'
    style = 'plain'
    foreground = '#22da6e'
    foreground_templates = ['{{ if gt .Code 0 }}#ef5350{{ end }}']
    template = ''

    [blocks.segments.properties]
      always_enabled = true

[transient_prompt]
  foreground = '#d6deeb'
  background = 'transparent'
  template = ' '
