[general]
import = [
  "/usr/lib/node_modules/alacritty-themes/themes/Catppuccin-Mocha.toml"
]
live_config_reload = true

[font]
size = 13

  [font.normal]
  family = "JetBrainsMono Nerd Font"
  style = "Regular"

  [font.bold]
  family = "JetBrainsMono Nerd Font"
  style = "Bold"

  [font.italic]
  family = "JetBrainsMono Nerd Font"

[terminal]
shell = "/bin/zsh"

[window]
opacity = 0.9

  [window.dimensions]
  columns = 160
  lines = 80

[cursor]
unfocused_hollow = false

[env]
TERM = "xterm-256color"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"
